name: finallab_santosla
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  fluttertoast: ^8.2.4
  firebase_auth: ^5.5.4
  image_picker: ^1.0.4
  uuid: ^4.0.0
  firebase_storage: ^12.4.6
  shimmer: ^2.0.0


dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bg1.png
    - assets/hnb_logo.png
    - assets/splashbg.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/hnb_logo.png"
