name: finallab_santosla
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.10.8
  cloud_firestore: ^4.5.0
  fluttertoast: ^8.2.4
  firebase_auth: ^4.17.0
  image_picker: ^1.0.4
  uuid: ^4.0.0
  firebase_storage: ^11.2.6


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bg1.png
    - assets/hnb_logo.png
    - assets/splashbg.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/hnb_logo.png"
